// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductManagement_API.Data;

#nullable disable

namespace ProductManagement_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_CategoryName_Unique");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Categories_IsActive");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Yến Sào Thô",
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yến sào tự nhiên chưa qua chế biến, giữ nguyên hình dạng ban đầu",
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Yến Sào Chưng",
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yến sào đã được chưng sẵn, tiện lợi cho việc sử dụng",
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Yến Sào Tinh Chế",
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yến sào đã được tinh chế và làm sạch, chất lượng cao",
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Phụ Kiện Chưng Yến",
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Các phụ kiện hỗ trợ chế biến yến sào như chén chưng, đường phèn",
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("InventoryId");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_Inventories_ProductId_Unique");

                    b.HasIndex("Quantity", "MinStockLevel")
                        .HasDatabaseName("IX_Inventories_Stock_Levels");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            MinStockLevel = 10,
                            Notes = "Initial inventory setup",
                            ProductId = 1,
                            Quantity = 50,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            InventoryId = 2,
                            MinStockLevel = 5,
                            Notes = "Initial inventory setup",
                            ProductId = 2,
                            Quantity = 30,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            InventoryId = 3,
                            MinStockLevel = 3,
                            Notes = "Initial inventory setup",
                            ProductId = 3,
                            Quantity = 20,
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Products_CategoryId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Products_IsActive");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("IX_Products_ProductName");

                    b.HasIndex("ProductType", "Origin")
                        .HasDatabaseName("IX_Products_Type_Origin");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yến sào thô cao cấp từ Khánh Hòa, hạng A, trọng lượng 100g. Sản phẩm tự nhiên 100%, không tẩy trắng, giàu dinh dưỡng.",
                            Grade = "A",
                            ImageUrl = "/images/products/yen-tho-kh-a-100g.jpg",
                            IsActive = true,
                            Origin = "Khánh Hòa",
                            Price = 2500000m,
                            ProductName = "Yến Sào Thô Khánh Hòa Hạng A 100g",
                            ProductType = "Thô",
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 100
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yến sào chưng sẵn từ Ninh Thuận, hạng B, trọng lượng 50g. Tiện lợi, dễ sử dụng.",
                            Grade = "B",
                            ImageUrl = "/images/products/yen-chung-nt-b-50g.jpg",
                            IsActive = true,
                            Origin = "Ninh Thuận",
                            Price = 800000m,
                            ProductName = "Yến Sào Chưng Ninh Thuận Hạng B 50g",
                            ProductType = "Chưng",
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 50
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yến sào tinh chế cao cấp từ Phú Yên, hạng A, trọng lượng 250g. Đã được làm sạch hoàn toàn.",
                            Grade = "A",
                            ImageUrl = "/images/products/yen-tinh-che-py-a-250g.jpg",
                            IsActive = true,
                            Origin = "Phú Yên",
                            Price = 5500000m,
                            ProductName = "Yến Sào Tinh Chế Phú Yên Hạng A 250g",
                            ProductType = "Tinh Chế",
                            UpdatedAt = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Weight = 250
                        });
                });

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Inventory", b =>
                {
                    b.HasOne("ProductManagement_API.Models.Entities.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("ProductManagement_API.Models.Entities.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Product", b =>
                {
                    b.HasOne("ProductManagement_API.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductManagement_API.Models.Entities.Product", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
